Commerce 4
craftcms/docs pull request #347
Opened 2022-03-12 03:36 UTC by mattstein

### Description

2022-03-15 16:14 UTC, lukeholder requested changes

2022-03-15 16:14 UTC, lukeholder commented on docs/commerce/4.x/upgrading.md
> +- custom address fields can be managed in field layouts—so no more need for `custom1`, `custom2`, etc.
Not sure if should go here, or under a description of what the `php craft commerce/upgrade` command does, but the command takes care of prompting you to choose (and create if needed) the custom fields that the old address data should me migrated to. It will do this for the following old address fields:

```attention
title
address3
businessId
phone
alternativePhone
custom1
custom2
custom3
custom4
notes
```

2022-03-15 16:14 UTC, lukeholder commented on docs/commerce/4.x/upgrading.md
> +## Subscriptions
I think the Plans CP URL changes should be left in the changelog? It's not ready a part of upgrading.

2022-03-15 16:14 UTC, lukeholder commented on docs/commerce/4.x/upgrading.md
> +
`discount.userGroupIds` has been removed and migrated into the discount's user condition builder.

2022-03-15 16:14 UTC, lukeholder commented on docs/commerce/4.x/upgrading.md
> +- your site’s running at least **Craft 4.0**
One cannot be on Craft 4 first as you would need to update all plugin versions in composer.json to 4.x at the same time?

2022-03-15 16:14 UTC, lukeholder commented on docs/commerce/4.x/upgrading.md
> +5. Run `php craft commerce/upgrade`.
We need to explain that this command is interactive and it will do the following:

1) Make sure you have already run the standard migration.
2) Let the user interactively map any custom countries to valid 2-letter country codes. (All addresses and zones will be updated from this mapping)
3) If any address in the system has data in any of these  fields: 

```
title
address3
businessId
phone
alternativePhone
custom1
custom2
custom3
custom4
notes
```
then they will be prompted to create a custom field (or choose the handle of an existing custom field). The data in the above fields will be migrated to custom fields.

4) All customers in the commerce system will be converted to users if they do not already have a related user existing.
5) All commerce addresses will be created as elements.
6) User addresses will be linked to the migrated address elements.
7) Order addresses will be linked to the migrated address elements
8) Primary billing and shipping IDs on the user are mapped to the address element IDs
9) Tax and shipping zones conditions are created and migrated from the old country and states lists.
10) Store location is connected to it's address element
11) Order history records are now linked directly to user accounts and not to commerce customers
12) Countries that were previously enabled are migrated to store countries,  and an address condition (Market locations) is created.

2022-03-15 16:14 UTC, lukeholder commented on docs/commerce/4.x/upgrading.md
> +This example is configured to only allow orders having addresses in the United States:
The example in the image is not a country condition but an administrative area condition with no states/provinces chosen.

2022-03-15 16:14 UTC, lukeholder commented on docs/commerce/4.x/upgrading.md
> +$countries = \craft\commerce\Plugin::getInstance()
See linear https://linear.app/craftcms/issue/DOC-221#comment-d079e8a5 response for clarification

2022-03-15 16:14 UTC, lukeholder commented on docs/commerce/4.x/upgrading.md
> +While Commerce has removed support for managing custom countries and states, the [`commerce/upgrade`](console-commands.md#commerce-upgrade) command migrates previous custom countries and states into
*upgrade command prompts you to map the custom countries to real country codes, and copies the state `abbreviation` (if custom state was created) or the `stateName` entered by the customer to the `administrativeArea` field on addresses, and zones.

2022-03-16 00:07 UTC, mattstein commented on docs/commerce/4.x/upgrading.md
> +## Subscriptions
👍

2022-03-16 00:07 UTC, mattstein commented on docs/commerce/4.x/upgrading.md
> +
👍 Mentioned in the table further down, under the “Models” heading.

2022-03-16 00:08 UTC, mattstein commented on docs/commerce/4.x/upgrading.md
> +- your site’s running at least **Craft 4.0**
This was silly. Removed.

2022-03-16 00:08 UTC, mattstein commented on docs/commerce/4.x/upgrading.md
> +This example is configured to only allow orders having addresses in the United States:
Fixed in newer example.

2022-03-16 00:50 UTC, mattstein commented on docs/commerce/4.x/upgrading.md
> +5. Run `php craft commerce/upgrade`.
Should be improved in https://github.com/craftcms/docs/commit/79056893443afefb5ea26f3c9bc7ab7b9a2b6e58, where hopefully my rewording is still accurate.

2022-03-16 01:13 UTC, mattstein commented on docs/commerce/4.x/upgrading.md
> +While Commerce has removed support for managing custom countries and states, the [`commerce/upgrade`](console-commands.md#commerce-upgrade) command migrates previous custom countries and states into
Put this in the wrong place at first, but I [think I’ve got it](https://github.com/craftcms/docs/commit/151cea0ee45332f9ba0c420948c440faf193af7d).

2022-03-16 02:05 UTC, mattstein commented on docs/commerce/4.x/upgrading.md
> +- custom address fields can be managed in field layouts—so no more need for `custom1`, `custom2`, etc.
[Described on the console commands page](https://github.com/craftcms/docs/pull/347/commits/79056893443afefb5ea26f3c9bc7ab7b9a2b6e58) and linked to it right from the beginning of the upgrade guide.

2022-03-16 18:44 UTC, merged